[2024-05-12T12:44:52.077+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T12:44:52.094+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL manual__2024-05-12T12:44:51.461420+00:00 [queued]>
[2024-05-12T12:44:52.104+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL manual__2024-05-12T12:44:51.461420+00:00 [queued]>
[2024-05-12T12:44:52.105+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2024-05-12T12:44:52.122+0000] {taskinstance.py:2327} INFO - Executing <Task(FivetranSensor): extract_load_fivetran.wait_for_EL> on 2024-05-12 12:44:51.461420+00:00
[2024-05-12T12:44:52.126+0000] {standard_task_runner.py:63} INFO - Started process 2771 to run task
[2024-05-12T12:44:52.128+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_transactions_pipeline', 'extract_load_fivetran.wait_for_EL', 'manual__2024-05-12T12:44:51.461420+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp3062k73i']
[2024-05-12T12:44:52.131+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask extract_load_fivetran.wait_for_EL
[2024-05-12T12:44:52.178+0000] {task_command.py:426} INFO - Running <TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL manual__2024-05-12T12:44:51.461420+00:00 [running]> on host f5da772b0226
[2024-05-12T12:44:52.268+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='mm22@gmail.com' AIRFLOW_CTX_DAG_OWNER='ct' AIRFLOW_CTX_DAG_ID='customer_transactions_pipeline' AIRFLOW_CTX_TASK_ID='extract_load_fivetran.wait_for_EL' AIRFLOW_CTX_EXECUTION_DATE='2024-05-12T12:44:51.461420+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-12T12:44:51.461420+00:00'
[2024-05-12T12:44:52.269+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T12:44:52.291+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T12:44:52.302+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/sensors.py", line 149, in execute
    elif not self.poke(context):
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/sensors.py", line 198, in poke
    self._completed_after_time_rendered = self.hook.get_last_sync(self.connector_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 406, in get_last_sync
    connector_details = self.get_connector(connector_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 210, in get_connector
    resp = self._do_api_call("GET", endpoint)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 152, in _do_api_call
    self.fivetran_conn = self.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fivetran_detault` isn't defined
[2024-05-12T12:44:52.306+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=customer_transactions_pipeline, task_id=extract_load_fivetran.wait_for_EL, execution_date=20240512T124451, start_date=20240512T124452, end_date=20240512T124452
[2024-05-12T12:44:52.317+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 37 for task extract_load_fivetran.wait_for_EL (The conn_id `fivetran_detault` isn't defined; 2771)
[2024-05-12T12:44:52.341+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T12:44:52.358+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T12:44:52.360+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
