[2024-05-12T12:19:07.954+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T12:19:07.979+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [queued]>
[2024-05-12T12:19:07.994+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [queued]>
[2024-05-12T12:19:07.995+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2024-05-12T12:19:08.019+0000] {taskinstance.py:2327} INFO - Executing <Task(FivetranSensor): extract_load_fivetran.wait_for_EL> on 2024-05-03 02:00:00+00:00
[2024-05-12T12:19:08.025+0000] {standard_task_runner.py:63} INFO - Started process 2157 to run task
[2024-05-12T12:19:08.028+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_transactions_pipeline', 'extract_load_fivetran.wait_for_EL', 'scheduled__2024-05-03T02:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpj2tjvhvq']
[2024-05-12T12:19:08.030+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask extract_load_fivetran.wait_for_EL
[2024-05-12T12:19:08.093+0000] {task_command.py:426} INFO - Running <TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [running]> on host f5da772b0226
[2024-05-12T12:19:08.210+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='mm22@gmail.com' AIRFLOW_CTX_DAG_OWNER='ct' AIRFLOW_CTX_DAG_ID='customer_transactions_pipeline' AIRFLOW_CTX_TASK_ID='extract_load_fivetran.wait_for_EL' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T02:00:00+00:00'
[2024-05-12T12:19:08.211+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T12:19:08.263+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T12:19:08.276+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/sensors.py", line 149, in execute
    elif not self.poke(context):
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/sensors.py", line 198, in poke
    self._completed_after_time_rendered = self.hook.get_last_sync(self.connector_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 406, in get_last_sync
    connector_details = self.get_connector(connector_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 210, in get_connector
    resp = self._do_api_call("GET", endpoint)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 152, in _do_api_call
    self.fivetran_conn = self.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fivetran_detault` isn't defined
[2024-05-12T12:19:08.283+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=customer_transactions_pipeline, task_id=extract_load_fivetran.wait_for_EL, execution_date=20240503T020000, start_date=20240512T121907, end_date=20240512T121908
[2024-05-12T12:19:08.297+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 11 for task extract_load_fivetran.wait_for_EL (The conn_id `fivetran_detault` isn't defined; 2157)
[2024-05-12T12:19:08.321+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T12:19:08.342+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T12:19:08.344+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-12T12:40:17.218+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T12:40:17.242+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [queued]>
[2024-05-12T12:40:17.256+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [queued]>
[2024-05-12T12:40:17.256+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2024-05-12T12:40:17.275+0000] {taskinstance.py:2327} INFO - Executing <Task(FivetranSensor): extract_load_fivetran.wait_for_EL> on 2024-05-03 02:00:00+00:00
[2024-05-12T12:40:17.282+0000] {standard_task_runner.py:63} INFO - Started process 2658 to run task
[2024-05-12T12:40:17.287+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_transactions_pipeline', 'extract_load_fivetran.wait_for_EL', 'scheduled__2024-05-03T02:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp1uaprsmm']
[2024-05-12T12:40:17.296+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask extract_load_fivetran.wait_for_EL
[2024-05-12T12:40:17.473+0000] {task_command.py:426} INFO - Running <TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [running]> on host f5da772b0226
[2024-05-12T12:40:17.619+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='mm22@gmail.com' AIRFLOW_CTX_DAG_OWNER='ct' AIRFLOW_CTX_DAG_ID='customer_transactions_pipeline' AIRFLOW_CTX_TASK_ID='extract_load_fivetran.wait_for_EL' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T02:00:00+00:00'
[2024-05-12T12:40:17.619+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T12:40:17.654+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T12:40:17.663+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/sensors.py", line 149, in execute
    elif not self.poke(context):
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/sensors.py", line 198, in poke
    self._completed_after_time_rendered = self.hook.get_last_sync(self.connector_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 406, in get_last_sync
    connector_details = self.get_connector(connector_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 210, in get_connector
    resp = self._do_api_call("GET", endpoint)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 152, in _do_api_call
    self.fivetran_conn = self.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fivetran_detault` isn't defined
[2024-05-12T12:40:17.670+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=customer_transactions_pipeline, task_id=extract_load_fivetran.wait_for_EL, execution_date=20240503T020000, start_date=20240512T124017, end_date=20240512T124017
[2024-05-12T12:40:17.686+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task extract_load_fivetran.wait_for_EL (The conn_id `fivetran_detault` isn't defined; 2658)
[2024-05-12T12:40:17.709+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T12:40:17.730+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T12:40:17.732+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-12T12:44:21.713+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T12:44:21.735+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [queued]>
[2024-05-12T12:44:21.746+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [queued]>
[2024-05-12T12:44:21.747+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 3
[2024-05-12T12:44:21.763+0000] {taskinstance.py:2327} INFO - Executing <Task(FivetranSensor): extract_load_fivetran.wait_for_EL> on 2024-05-03 02:00:00+00:00
[2024-05-12T12:44:21.771+0000] {standard_task_runner.py:63} INFO - Started process 2753 to run task
[2024-05-12T12:44:21.776+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_transactions_pipeline', 'extract_load_fivetran.wait_for_EL', 'scheduled__2024-05-03T02:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9_chfsvv']
[2024-05-12T12:44:21.779+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask extract_load_fivetran.wait_for_EL
[2024-05-12T12:44:21.853+0000] {task_command.py:426} INFO - Running <TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [running]> on host f5da772b0226
[2024-05-12T12:44:21.964+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='mm22@gmail.com' AIRFLOW_CTX_DAG_OWNER='ct' AIRFLOW_CTX_DAG_ID='customer_transactions_pipeline' AIRFLOW_CTX_TASK_ID='extract_load_fivetran.wait_for_EL' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T02:00:00+00:00'
[2024-05-12T12:44:21.965+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T12:44:21.987+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T12:44:21.996+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/sensors.py", line 149, in execute
    elif not self.poke(context):
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/sensors.py", line 198, in poke
    self._completed_after_time_rendered = self.hook.get_last_sync(self.connector_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 406, in get_last_sync
    connector_details = self.get_connector(connector_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 210, in get_connector
    resp = self._do_api_call("GET", endpoint)
  File "/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/hooks.py", line 152, in _do_api_call
    self.fivetran_conn = self.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fivetran_detault` isn't defined
[2024-05-12T12:44:22.000+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=customer_transactions_pipeline, task_id=extract_load_fivetran.wait_for_EL, execution_date=20240503T020000, start_date=20240512T124421, end_date=20240512T124421
[2024-05-12T12:44:22.012+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task extract_load_fivetran.wait_for_EL (The conn_id `fivetran_detault` isn't defined; 2753)
[2024-05-12T12:44:22.029+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-12T12:44:22.046+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T12:44:22.048+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-12T12:53:39.135+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T12:53:39.155+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [queued]>
[2024-05-12T12:53:39.164+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [queued]>
[2024-05-12T12:53:39.165+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-12T12:53:39.180+0000] {taskinstance.py:2327} INFO - Executing <Task(FivetranSensor): extract_load_fivetran.wait_for_EL> on 2024-05-03 02:00:00+00:00
[2024-05-12T12:53:39.184+0000] {standard_task_runner.py:63} INFO - Started process 2978 to run task
[2024-05-12T12:53:39.187+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_transactions_pipeline', 'extract_load_fivetran.wait_for_EL', 'scheduled__2024-05-03T02:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpwvpi2qx5']
[2024-05-12T12:53:39.189+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask extract_load_fivetran.wait_for_EL
[2024-05-12T12:53:39.246+0000] {task_command.py:426} INFO - Running <TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [running]> on host f5da772b0226
[2024-05-12T12:53:39.338+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='mm22@gmail.com' AIRFLOW_CTX_DAG_OWNER='ct' AIRFLOW_CTX_DAG_ID='customer_transactions_pipeline' AIRFLOW_CTX_TASK_ID='extract_load_fivetran.wait_for_EL' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-03T02:00:00+00:00'
[2024-05-12T12:53:39.339+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T12:53:39.366+0000] {base.py:84} INFO - Using connection ID 'fivetran_default' for task execution.
[2024-05-12T12:53:40.794+0000] {hooks.py:487} INFO - Connector rescue_aerobics: sync_state = scheduled
[2024-05-12T12:53:40.795+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T12:53:40.796+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-12T12:53:40.803+0000] {taskinstance.py:2486} INFO - Pausing task as DEFERRED. dag_id=customer_transactions_pipeline, task_id=extract_load_fivetran.wait_for_EL, execution_date=20240503T020000, start_date=20240512T125339
[2024-05-12T12:53:40.846+0000] {local_task_job_runner.py:237} INFO - Task exited with return code 100 (task deferral)
[2024-05-12T12:53:40.847+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-12T12:54:46.050+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-12T12:54:46.066+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [queued]>
[2024-05-12T12:54:46.074+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [queued]>
[2024-05-12T12:54:46.075+0000] {taskinstance.py:2301} INFO - Resuming after deferral
[2024-05-12T12:54:46.087+0000] {taskinstance.py:2327} INFO - Executing <Task(FivetranSensor): extract_load_fivetran.wait_for_EL> on 2024-05-03 02:00:00+00:00
[2024-05-12T12:54:46.091+0000] {standard_task_runner.py:63} INFO - Started process 3017 to run task
[2024-05-12T12:54:46.093+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'customer_transactions_pipeline', 'extract_load_fivetran.wait_for_EL', 'scheduled__2024-05-03T02:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp3isl0aao']
[2024-05-12T12:54:46.095+0000] {standard_task_runner.py:91} INFO - Job 50: Subtask extract_load_fivetran.wait_for_EL
[2024-05-12T12:54:46.140+0000] {task_command.py:426} INFO - Running <TaskInstance: customer_transactions_pipeline.extract_load_fivetran.wait_for_EL scheduled__2024-05-03T02:00:00+00:00 [running]> on host f5da772b0226
[2024-05-12T12:54:46.202+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-12T12:54:46.203+0000] {sensors.py:221} INFO - Fivetran connector rescue_aerobics finished syncing at 2024-05-12 12:54:18.991000+00:00
[2024-05-12T12:54:46.204+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-12T12:54:46.212+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=customer_transactions_pipeline, task_id=extract_load_fivetran.wait_for_EL, execution_date=20240503T020000, start_date=20240512T125339, end_date=20240512T125446
[2024-05-12T12:54:46.226+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-12T12:54:46.241+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-12T12:54:46.243+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
